# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 레이블
labels:
  'bug':
    include:
      - '\bfix\b'
      - '\bbugfix\b'
      - '\bbug\b'
  'test':
    include:
      - '\btest\b'
  'feature':
    include:
      - '\bfeat\b'
      - '\benhancement\b'
  'documentation':
    include:
      - '\bdocs\b'
  'chore':
    include:
      - '\bchore\b'
  'do not merge':
    include:
      - '\bdo not merge\b'
  